### ISSUE TITLE
update-codegen is not working properly after updating k8s.io/code-generator to version 0.30.0 or higher

### ISSUE THREAD

**Issue by TaiPark** [volcano-sh/apis#133]
**Describe the bug**
Due to the update https://github.com/kubernetes/kubernetes/pull/123529 of K8S, many syntax changes have occurred in the code-generator.
Moreover, in https://github.com/kubernetes/kubernetes/commit/1a4450f6ffdad44bfc12fae5911c93e3bd238f0f, the location of openapi-gen has also been replaced.
After the update https://github.com/volcano-sh/apis/pull/129, the current update-codegen.sh of volcano-apis can no longer function properly.
Additionally, based on the observation https://github.com/kubernetes/kubernetes/commit/7776496309c49f91c15ca929d6e27442ae6b83dc, the K8S community has ceased maintenance of `generate-groups.sh` and `generate-internal-groups.sh`, and has instead started to maintain `kube_codegen.sh` since https://github.com/kubernetes/kubernetes/pull/117262.
Is the volcano-apis community considering replacing the current codegen script with `kube_codegen.sh`?

**To Reproduce**
```sh
bash ./hack/update-codegen.sh
```
![image](https://github.com/user-attachments/assets/24957cf0-8d36-4887-b225-ddfdc6268c97)

**Comment by Monokaix** [comment]
That's necessary and great! We should keep consistent with k8s, the current code generation script was also copyed from k8s.
