### ISSUE TITLE
Why are there two definition files of Queue and PodGroup in the apis/scheduling directory?

### ISSUE THREAD

**Issue by D0m021ng** [volcano-sh/apis#43]
There are two definition files of Queue and PodGroup in the apis/scheduling directory, such as apis/scheduling/types.go and apis/scheduling/v1beta1/types.go. Both files are used in the code.  Are there any design considerations？

**Comment by Thor-wl** [comment]
I think they can be merged as one.

**Comment by k82cn** [comment]
`apis/scheduling/types.go` does not include version, `apis/scheduling/v1beta1/types.go` has version info.

**Comment by D0m021ng** [comment]
Thanks for your answer.
